### ISSUE TITLE
天气预报更改不能保存？

### ISSUE THREAD

**Issue by d975xbx** [openwrtcompileshell/OpenwrtCompileScript#10]
天气预报更改不能保存

**Comment by ITdesk01** [comment]
脑补失败，描述不清楚，拒绝回答

**Comment by EuropeanWithSSR** [comment]
> 脑补失败，描述不清楚，拒绝回答

更改为对应城市后，的确显示为对应城市，但刷新又变回深圳。
使用的路由器为k2p，固件为lean r9最新，换用多个浏览器均出现此问题。

**Comment by EuropeanWithSSR** [comment]
> 天气预报更改不能保存

我目前的解决方法是进入/usr/lib/lua/luci/view/admin_status，编辑 index.htm，搜索“shenzhen”，改成你所在城市的拼音。如果更改后不正确的话，可能是由于拼音与其它城市相同，可以去https://www.tianqi.com，切换为你所在的城市，复制地址栏“https://www.tianqi.com/”后的拼音和数字，去掉最后一个斜杠，用它替换 index.htm 里的 “shenzhen”。
比如，如果你住在江西的丰城，拼音与辽宁的凤城相同，则在 tianqi.com 里，用 ”fengcheng1“ 作为了代替。你用“fengcheng1”替换”shenzhen“，就可以使默认天气变为丰城而不是辽宁凤城。

**Comment by ITdesk01** [comment]
确实没有写入的操作，如果你只需要显示一个城市，你可以修改我的文件然后编译出来就行了
修改这个目录底下的Openwrt/Script_File/OpenwrtCompileScript/Warehouse/index_Weather/index.htm
然后编译出来固件就可以解决你的问题

**Comment by ITdesk01** [comment]
我已经合并EuropeanWithSSR的提交了，你测试一下，我在我路由测试正常
