### ISSUE TITLE
最新版本从远端获取openwrt更新后运行出现错误

### ISSUE THREAD

**Issue by a1768623020** [openwrtcompileshell/OpenwrtCompileScript#11]
![2020-02-18 15-51-10屏幕截图](https://user-images.githubusercontent.com/32887476/74715387-4a4eaa80-5267-11ea-8e06-6ed3ebf0f73e.png)
卡到这里就不向下继续运行了，也无法结束当前进程。

**Comment by ITdesk01** [comment]
建议你使用电脑端的软件去运行命令，你这个手机端我没有试过

**Comment by a1768623020** [comment]
我给你截一张完整的截图吧。。。
![2020-03-04 224856](https://user-images.githubusercontent.com/32887476/75892468-51cba180-5e6c-11ea-960b-15ba360e27d5.jpg)
ubuntu18.04.03

**Comment by ITdesk01** [comment]
> 我给你截一张完整的截图吧。。。 ubuntu18.04.03
> ![2020-03-04 224856](https://user-images.githubusercontent.com/32887476/75892468-51cba180-5e6c-11ea-960b-15ba360e27d5.jpg)

我觉得还是你的软件问题，我在ubuntu18.4测试一切正常
