### ISSUE TITLE
无法下载DL包

### ISSUE THREAD

**Issue by cntink** [openwrtcompileshell/OpenwrtCompileScript#12]
-------------------------------------
	      	    【 5.其他选项 】

 		  1 只搭建编译环境，不进行编译

		  2 单独Download DL库 

		  3 更新lean软件库 

		  4 下载额外的插件 

		  0. 回到上一级菜单

		PS:请先搭建好梯子再进行编译，不然很慢！
			     By:ITdesk
	      --------------------------------------
请输入数字:2

***你的openwrt文件夹有以下几个***
openwrt

请输入你的文件夹（记得区分大小写）：openwrt

ubuntu@ubuntu:~$

**Comment by ITdesk01** [comment]
已经修复
