### ISSUE TITLE
WSL2 Ubuntu 18.04 会遇到 feeds 不能更新的情况

### ISSUE THREAD

**Issue by EuropeanWithSSR** [openwrtcompileshell/OpenwrtCompileScript#15]
![image](https://user-images.githubusercontent.com/39738950/76181842-8f7a5280-61fd-11ea-8742-d5696f8ac19e.png)
手动在下载的固件文件夹内执行 ./scripts/feeds update -a 会出现如下情况提示：
![image](https://user-images.githubusercontent.com/39738950/76181953-eda73580-61fd-11ea-9a07-a8609316510b.png)
运行这个 issue 里提到的命令后，就可以正常下载 feeds 了。https://github.com/coolsnowwolf/lede/issues/3652
![image](https://user-images.githubusercontent.com/39738950/76182159-d452b900-61fe-11ea-9957-c5e668237dd0.png)
![image](https://user-images.githubusercontent.com/39738950/76182165-e59bc580-61fe-11ea-8b3f-eaa526c046e3.png)
原以为是脚本漏装了一些东西，但仔细一看发现这个 issue 给出的命令中的所有包都已经写在了 rely_on() 里。
不太明白到底是什么原因导致单独运行脚本不能够安装这些包的部分或全部。
值得一提的是，单独运行该 issue 给出的命令时，曾有一个如图所示的要求确认提示，我选择了是。不知是否与脚本没有成功安装有关。
![image](https://user-images.githubusercontent.com/39738950/76182613-83dc5b00-6200-11ea-8c40-bb3536071efd.png)
跟一个还算对 Linux 比较了解朋友交流了很久也没弄明白为什么，特来请教。

另外，wsl 编译时，还遇到这个问题，希望大大能把这条命令加到脚本里去。https://github.com/coolsnowwolf/lede/issues/3295#issuecomment-590061019

**Comment by ITdesk01** [comment]
已经引用，测试完成，告诉我一下结果，我的编译机就不折腾了，没那么大的空间

**Comment by EuropeanWithSSR** [comment]
> 已经引用，测试完成，告诉我一下结果，我的编译机就不折腾了，没那么大的空间

还有一个问题就是 wsl2 脚本不能识别，所以 sudo apt-get install 那几个包加在识别子系统后对 wsl2 是没有作用的。

**Comment by EuropeanWithSSR** [comment]
切换成 wsl1 也没有解决不能更新 feeds 的问题

**Comment by ITdesk01** [comment]
> 切换成wsl1也没有解决不能更新feeds的问题

wsl 1我测试的时候是正常的，如果无法描述清楚，你可以把他录制成视频，我看看

**Comment by EuropeanWithSSR** [comment]
> > 切换成wsl1也没有解决不能更新feeds的问题
> 
> wsl 1我测试的时候是正常的，如果无法描述清楚，你可以把他录制成视频，我看看

视频下载：https://c-t.work/s/0550438533734b 
YouTube（需等待画质优化）：https://youtu.be/iRBY4I-mn-8

**Comment by EuropeanWithSSR** [comment]
![image](https://user-images.githubusercontent.com/39738950/76238143-5f1ccd80-626a-11ea-8cc0-3456c9787d48.png)
经人指点，之前的截图中，单独运行 rely_on 里的命令，有提示 unable to locate package linux-libc-dev:i386，刚刚在 openwrt.sh 里删掉 linux-libc-dev:i386 后，就正常了。

**Comment by EuropeanWithSSR** [comment]
https://github.com/coolsnowwolf/lede/issues/3453#issuecomment-593168270

**Comment by ITdesk01** [comment]
再重新测试一下wsl1，   wsl2和wsl1你帮我输一下命令cat /proc/version，然后把结果给我

**Comment by EuropeanWithSSR** [comment]
WSL1还是同样的问题
![image](https://user-images.githubusercontent.com/39738950/76279611-1dbc0a80-62ca-11ea-9f15-cf8c43cd193a.png)

cat /proc/version
WSL1: 
Linux version 4.4.0-19041-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Fri Dec 06 14:06:00 PST 2019
WSL2:
Linux version 4.19.84-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Nov 13 11:44:37 UTC 2019

**Comment by ITdesk01** [comment]
测试脚本之前把此文件移位 /etc/apt/sources.list.back

**Comment by EuropeanWithSSR** [comment]
已经没有问题了

**Comment by ITdesk01** [comment]
好的
