### ISSUE TITLE
问个关于gitpod的问题，这个东西是不是只有15GB使用空间啊~

### ISSUE THREAD

**Issue by Lrvineshaw** [openwrtcompileshell/OpenwrtCompileScript#17]
![优效截图20200328220031](https://user-images.githubusercontent.com/34879145/77824767-fc6b7300-713f-11ea-8c50-8aebaeb28da2.png)

如图只能使用workspace目录的空间，其他目录进去了也都不能使用，全都被系统设置为read-only了，15GB的话编译固件空间不够啊

**Comment by ITdesk01** [comment]
自行查阅官方文档
