### ISSUE TITLE
未绑定的变量

### ISSUE THREAD

**Issue by kenen** [openwrtcompileshell/OpenwrtCompileScript#18]
A    package/other-plugins/luci-app-passwall/root/usr/share/passwall/test.sh
取出版本 1792。
取出版本 1792。
取出版本 1792。
grep: package/other-plugins/luci-app-passwall/luasrc/controller/fileassistant.lua: 没有那个文件或目录
/home/kennen/Openwrt/Script_File/OpenwrtCompileScript/openwrt.sh: 行 1349: fileassistant_display: 未绑定的变量

**Comment by ITdesk01** [comment]
请更新脚本，这个已经解决了
