### ISSUE TITLE
源码地址仓库第一个R8是不是应该取消，地址库不存在了

### ISSUE THREAD

**Issue by baoguwei** [openwrtcompileshell/OpenwrtCompileScript#20]
反馈bug/问题模板，提建议请删除

## 一.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：

### (2) 步骤重现

A：

### (3) 无法描述清楚，请图片或者视频

A：

**Comment by ITdesk01** [comment]
旧地址看起来没有失效，为了区分我改下名称和地址吧
