### ISSUE TITLE
verysync-linux-amd64-v1.4.3.tar.gz 这个包 下载以后打不开 导致编译错误

### ISSUE THREAD

**Issue by ptsa** [openwrtcompileshell/OpenwrtCompileScript#21]
verysync-linux-amd64-v1.4.3.tar.gz
这个包 下载以后打不开 导致编译错误
新版本是不是1.4.4

**Comment by ITdesk01** [comment]
dl的包全部都是make download 以后下载的，调用的是openwrt自己的下载地址，跟脚本无关，出现这种情况多半是网络问题导致包不完整自己删除，重新下载
