### ISSUE TITLE
默认设置的一些疑问

### ISSUE THREAD

**Issue by ptsa** [openwrtcompileshell/OpenwrtCompileScript#23]
比如ipv6支持 和docker

docker 我再配置文件里面取消以后 还是会编译？

**Comment by ITdesk01** [comment]
配置文件自己取消luci-app-dockeman 。IPV6取消ipv6helper，在下次你更新源码之前，应该都不会变化，当然这是针对同一个配置，其他配置文件你需要重复做这个操作，或者你可禁用脚本里的相关代码，达到一劳永逸的效果

**Comment by ptsa** [comment]
那你能不能写个配置文件， 可以设置默认关不关这些，可以做个选择

**Comment by ITdesk01** [comment]
首先你要明白一点，openwrt本身就有默认配置文件，我脚本做的就是把他优化成我想要的，反而言之你也可以通过修改脚本代码达到你想要的目的，至于你说的默认关不关这个选项，make menconfig这个界面你就可以做到你想要的的，我又何必多此一举？？？

**Comment by ptsa** [comment]
使用 make menconfig 后保存的文件  对你更新脚本的docker 启用和 ipve6 取消 没有影响的对吧

**Comment by ITdesk01** [comment]
make menconfig 无论怎么修改，对我脚本没有一点影响，我的脚本工作只是辅助而已，调用的还是源码本身，举个例子吧，你在make menuconfig 取消了docke 和ipv6 ，在你不删除这个机型配置文件，和更新源码的前提下，下次编译还是老样子，大概就这些自己试试就知道了
