### ISSUE TITLE
wsl Ubuntu 18.04 lts 出现 check_system: unbound variable

### ISSUE THREAD

**Issue by EuropeanWithSSR** [openwrtcompileshell/OpenwrtCompileScript#4]
![image](https://user-images.githubusercontent.com/39738950/69695846-b615f100-1118-11ea-811e-dbbc01e9dd12.png)
运行bash $openwrt时出现，进入OpenwrtCompileScript运行bash openwrt.sh也是一样。
尝试过通过win10的设置里重置Ubuntu，依然会出现。
手动进入lede文件夹可以成功编译。

**Comment by ITdesk01** [comment]
已经修复，请执行以下命令更新测试
cd $HOME/Openwrt/Script_File/OpenwrtCompileScript && git pull && bash $openwrt
