### ISSUE TITLE
编译了至少3次，只有插件，没有固件。。。

### ISSUE THREAD

**Issue by adaaaaaa** [openwrtcompileshell/OpenwrtCompileScript#5]
第四次报错，才看到了哪里问题。。。

make[5]: *** No rule to make target 'tools/objtool/objtool', needed by '/workspace/OpenwrtCompileScript/Openwrt/Lean/lede/build_dir/target-x86_64_musl/linux-x86_64/sched-cake-2019-03-12-057c7388/sch_cake.o'.  Stop.
make[4]: *** [Makefile:1523: _module_/workspace/OpenwrtCompileScript/Openwrt/Lean/lede/build_dir/target-x86_64_musl/linux-x86_64/sched-cake-2019-03-12-057c7388] Error 2
make[3]: *** [Makefile:46: /workspace/OpenwrtCompileScript/Openwrt/Lean/lede/build_dir/target-x86_64_musl/linux-x86_64/sched-cake-2019-03-12-057c7388/.built] Error 2
make[3]: Leaving directory '/workspace/OpenwrtCompileScript/Openwrt/Lean/lede/package/kernel/kmod-sched-cake'
make[2]: *** [package/Makefile:109: package/kernel/kmod-sched-cake/compile] Error 2
make[1]: *** [package/Makefile:103: /workspace/OpenwrtCompileScript/Openwrt/Lean/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make: *** [/workspace/OpenwrtCompileScript/Openwrt/Lean/lede/include/toplevel.mk:218: world] Error 2

怎么回事？我本地虚拟机编译都没有遇到过这样的问题。。。
Actions也没有这样的问题。。。

**Comment by ITdesk01** [comment]
x86的在云编译平台有点问题，具体没时间测试，上面好像差了点东西
