### ISSUE TITLE
 Public配置处理SSR P+可能有 问题..

### ISSUE THREAD

**Issue by fbrav530** [openwrtcompileshell/OpenwrtCompileScript#8]
在进入到make menuconfig后 不管选不选SSR P+的ssr服务端插件，都会默认编译，导致固件文件增大，最后因为固件大小超过了，出不来.bin  而在本地机器上，选同样配置可以出.bin

**Comment by ITdesk01** [comment]
你取消选择55r还会导致编译固件增大吗？？？
